copy .\English\*.tex *.tex

copy .\RChunks\GenericSettings.Rnw + .\English\Citation.Rnw Citation.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\Additional001.Rnw + .\RChunks\Additional002.Rnw + .\English\Additional003.Rnw + .\RChunks\Additional004.Rnw + .\English\Additional005.Rnw + .\RChunks\Additional006.Rnw + .\English\Additional007.Rnw + .\RChunks\Additional008.Rnw + .\English\Additional009.Rnw + .\RChunks\Additional010.Rnw + .\English\Additional011.Rnw + .\RChunks\CleanUp.Rnw Additional.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\ANOVA001.Rnw + .\RChunks\ANOVA002.Rnw + .\English\ANOVA003.Rnw + .\RChunks\ANOVA004.Rnw + .\English\ANOVA005.Rnw + .\RChunks\CleanUp.Rnw ANOVA.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\BasicInference001.Rnw + .\RChunks\BasicInference002.Rnw + .\English\BasicInference003.Rnw + .\RChunks\BasicInference004.Rnw + .\English\BasicInference005.Rnw + .\RChunks\BasicInference006.Rnw + .\English\BasicInference007.Rnw + .\RChunks\BasicInference008.Rnw + .\English\BasicInference009.Rnw + .\RChunks\BasicInference010.Rnw + .\English\BasicInference011.Rnw + .\RChunks\BasicInference012.Rnw + .\English\BasicInference013.Rnw + .\RChunks\BasicInference014.Rnw + .\English\BasicInference015.Rnw + .\RChunks\BasicInference016.Rnw + .\English\BasicInference017.Rnw + .\RChunks\BasicInference018.Rnw + .\English\BasicInference019.Rnw + .\RChunks\BasicInference020.Rnw + .\English\BasicInference021.Rnw + .\RChunks\BasicInference022.Rnw + .\English\BasicInference023.Rnw + .\RChunks\BasicInference024.Rnw + .\English\BasicInference025.Rnw + .\RChunks\CleanUp.Rnw BasicInference.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\BlindUse.rnw BlindUse.rnw

copy .\RChunks\GenericSettings.Rnw + .\English\Calculus001.Rnw + .\RChunks\Calculus002.Rnw + .\English\Calculus003.Rnw + .\RChunks\Calculus004.Rnw + .\English\Calculus005.Rnw + .\RChunks\Calculus006.Rnw + .\English\Calculus007.Rnw + .\RChunks\Calculus008.Rnw + .\English\Calculus009.Rnw + .\RChunks\CleanUp.Rnw Calculus.Rnw


copy .\RChunks\GenericSettings.Rnw + .\English\ComplexGraphs001.Rnw + .\RChunks\ComplexGraphs002.Rnw + .\English\ComplexGraphs003.Rnw + .\RChunks\ComplexGraphs004.Rnw + .\English\ComplexGraphs005.Rnw + .\RChunks\ComplexGraphs006.Rnw + .\English\ComplexGraphs007.Rnw + .\RChunks\ComplexGraphs008.Rnw + .\English\ComplexGraphs009.Rnw + .\RChunks\ComplexGraphs010.Rnw + .\English\ComplexGraphs011.Rnw + .\RChunks\ComplexGraphs012.Rnw + .\English\ComplexGraphs013.Rnw + .\RChunks\ComplexGraphs014.Rnw + .\English\ComplexGraphs015.Rnw + .\RChunks\ComplexGraphs016.Rnw + .\English\ComplexGraphs017.Rnw + .\RChunks\ComplexGraphs018.Rnw + .\English\ComplexGraphs019.Rnw + .\RChunks\ComplexGraphs020.Rnw + .\English\ComplexGraphs021.Rnw + .\RChunks\ComplexGraphs022.Rnw + .\English\ComplexGraphs023.Rnw + .\RChunks\ComplexGraphs024.Rnw + .\English\ComplexGraphs025.Rnw + .\RChunks\ComplexGraphs026.Rnw + .\English\ComplexGraphs027.Rnw + .\RChunks\ComplexGraphs028.Rnw + .\English\ComplexGraphs029.Rnw + .\RChunks\ComplexGraphs030.Rnw + .\English\ComplexGraphs031.Rnw + .\RChunks\ComplexGraphs032.Rnw + .\English\ComplexGraphs033.Rnw + .\RChunks\ComplexGraphs034.Rnw + .\English\ComplexGraphs035.Rnw + .\RChunks\ComplexGraphs036.Rnw + .\English\ComplexGraphs037.Rnw + .\RChunks\CleanUp.Rnw ComplexGraphs.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\DataEntry001.Rnw + .\English\DataEntry003.Rnw + .\RChunks\DataEntry004.Rnw + .\English\DataEntry005.Rnw + .\RChunks\DataEntry006.Rnw + .\English\DataEntry007.Rnw + .\RChunks\DataEntry008.Rnw + .\English\DataEntry009.Rnw + .\RChunks\DataEntry010.Rnw + .\English\DataEntry011.Rnw + .\RChunks\DataEntry012.Rnw + .\English\DataEntry013.Rnw + .\RChunks\DataEntry014.Rnw + .\English\DataEntry015.Rnw + .\RChunks\DataEntry016.Rnw + .\English\DataEntry017.Rnw + .\RChunks\DataEntry018.Rnw + .\English\DataEntry019.Rnw + .\RChunks\DataEntry020.Rnw + .\English\DataEntry021.Rnw + .\RChunks\DataEntry022.Rnw + .\English\DataEntry023.Rnw + .\RChunks\DataEntry024.Rnw + .\English\DataEntry025.Rnw + .\RChunks\DataEntry026.Rnw + .\English\DataEntry027.Rnw + .\RChunks\DataEntry028.Rnw + .\English\DataEntry029.Rnw + .\RChunks\DataEntry030.Rnw + .\English\DataEntry031.Rnw + .\RChunks\DataEntry032.Rnw + .\English\DataEntry033.Rnw + .\RChunks\DataEntry034.Rnw + .\English\DataEntry035.Rnw + .\RChunks\DataEntry036.Rnw + .\English\DataEntry037.Rnw + .\RChunks\DataEntry038.Rnw + .\English\DataEntry039.Rnw + .\RChunks\DataEntry040.Rnw + .\English\DataEntry041.Rnw + .\RChunks\DataEntry042.Rnw + .\English\DataEntry043.Rnw + .\RChunks\DataEntry044.Rnw + .\English\DataEntry045.Rnw + .\RChunks\DataEntry046.Rnw + .\English\DataEntry047.Rnw + .\RChunks\DataEntry048.Rnw + .\English\DataEntry049.Rnw + .\RChunks\DataEntry050.Rnw + .\English\DataEntry051.Rnw + .\RChunks\DataEntry052.Rnw + .\English\DataEntry053.Rnw + .\RChunks\DataEntry054.Rnw + .\English\DataEntry055.Rnw + .\RChunks\DataEntry056.Rnw + .\English\DataEntry057.Rnw + .\RChunks\DataEntry058.Rnw + .\English\DataEntry059.Rnw + .\RChunks\CleanUp.Rnw DataEntry.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\ExportData001.Rnw + .\English\ExportData003.Rnw + .\RChunks\ExportData004.Rnw + .\English\ExportData005.Rnw + .\RChunks\ExportData006.Rnw + .\English\ExportData007.Rnw + .\RChunks\CleanUp.Rnw ExportData.Rnw


copy .\RChunks\GenericSettings.Rnw + .\English\Functions001.Rnw + .\RChunks\Functions002.Rnw + .\English\Functions003.Rnw + .\RChunks\Functions004.Rnw + .\English\Functions005.Rnw + .\RChunks\Functions006.Rnw + .\English\Functions007.Rnw + .\RChunks\Functions008.Rnw + .\English\Functions009.Rnw + .\RChunks\CleanUp.Rnw Functions.Rnw


copy .\RChunks\GenericSettings.Rnw + .\English\GoodIdeas001.Rnw + .\English\GoodIdeas003.Rnw + .\RChunks\CleanUp.Rnw GoodIdeas.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\ImportData001.Rnw + .\English\ImportData003.Rnw + .\RChunks\ImportData004.Rnw + .\English\ImportData005.Rnw + .\RChunks\ImportData006.Rnw + .\English\ImportData007.Rnw + .\RChunks\ImportData008.Rnw + .\English\ImportData009.Rnw + .\RChunks\GetWD.Rnw + .\English\ImportData011.Rnw + .\RChunks\ImportData012.Rnw + .\English\ImportData013.Rnw + .\RChunks\ImportData014.Rnw + .\English\ImportData015.Rnw + .\RChunks\ImportData016.Rnw + .\English\ImportData017.Rnw + .\RChunks\ImportData018.Rnw + .\English\ImportData019.Rnw + .\RChunks\ImportData020.Rnw + .\English\ImportData021.Rnw + .\RChunks\CleanUp.Rnw ImportData.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\Intro001.Rnw + .\English\Intro003.Rnw + .\RChunks\CleanUp.Rnw Intro.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\KeepUseful001.Rnw + .\RChunks\KeepUseful002.Rnw + .\English\KeepUseful003.Rnw + .\RChunks\KeepUseful004.Rnw + .\English\KeepUseful005.Rnw + .\RChunks\KeepUseful006.Rnw + .\English\KeepUseful007.Rnw + .\RChunks\KeepUseful008.Rnw + .\English\KeepUseful009.Rnw + .\RChunks\KeepUseful010.Rnw + .\English\KeepUseful011.Rnw + .\RChunks\KeepUseful012.Rnw + .\English\KeepUseful013.Rnw + .\RChunks\CleanUp.Rnw KeepUseful.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\LinearAlgebra001.Rnw + .\RChunks\LinearAlgebra002.Rnw + .\English\LinearAlgebra003.Rnw + .\RChunks\LinearAlgebra004.Rnw + .\English\LinearAlgebra005.Rnw + .\RChunks\LinearAlgebra006.Rnw + .\English\LinearAlgebra007.Rnw + .\RChunks\LinearAlgebra008.Rnw + .\English\LinearAlgebra009.Rnw + .\RChunks\LinearAlgebra010.Rnw + .\English\LinearAlgebra011.Rnw + .\RChunks\LinearAlgebra012.Rnw + .\English\LinearAlgebra013.Rnw + .\RChunks\LinearAlgebra014.Rnw + .\English\LinearAlgebra015.Rnw + .\RChunks\LinearAlgebra016.Rnw + .\English\LinearAlgebra017.Rnw + .\RChunks\LinearAlgebra018.Rnw + .\English\LinearAlgebra019.Rnw + .\RChunks\LinearAlgebra020.Rnw + .\English\LinearAlgebra021.Rnw + .\RChunks\LinearAlgebra022.Rnw + .\English\LinearAlgebra023.Rnw + .\RChunks\LinearAlgebra024.Rnw + .\English\LinearAlgebra025.Rnw + .\RChunks\LinearAlgebra026.Rnw + .\English\LinearAlgebra027.Rnw + .\RChunks\LinearAlgebra028.Rnw + .\English\LinearAlgebra029.Rnw + .\RChunks\LinearAlgebra030.Rnw + .\English\LinearAlgebra031.Rnw + .\RChunks\LinearAlgebra032.Rnw + .\English\LinearAlgebra033.Rnw + .\RChunks\LinearAlgebra034.Rnw + .\English\LinearAlgebra035.Rnw + .\RChunks\LinearAlgebra036.Rnw + .\RChunks\CleanUp.Rnw LinearAlgebra.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\Manipulate001.Rnw + .\RChunks\Manipulate002.Rnw + .\English\Manipulate003.Rnw + .\RChunks\Manipulate004.Rnw + .\English\Manipulate005.Rnw + .\RChunks\Manipulate006.Rnw + .\English\Manipulate007.Rnw + .\RChunks\Manipulate008.Rnw + .\English\Manipulate009.Rnw + .\RChunks\Manipulate010.Rnw + .\English\Manipulate011.Rnw + .\RChunks\Manipulate012.Rnw + .\English\Manipulate013.Rnw + .\RChunks\Manipulate014.Rnw + .\English\Manipulate015.Rnw + .\RChunks\Manipulate016.Rnw + .\English\Manipulate017.Rnw + .\RChunks\Manipulate018.Rnw + .\English\Manipulate019.Rnw + .\RChunks\Manipulate020.Rnw + .\English\Manipulate021.Rnw + .\RChunks\dplyr.Rnw + .\English\Manipulate023.Rnw + .\RChunks\Manipulate024.Rnw + .\English\Manipulate025.Rnw + .\RChunks\Manipulate026.Rnw + .\English\Manipulate027.Rnw + .\RChunks\Manipulate028.Rnw + .\English\Manipulate029.Rnw + .\RChunks\Manipulate030.Rnw + .\English\Manipulate031.Rnw + .\RChunks\Manipulate032.Rnw + .\English\Manipulate033.Rnw + .\RChunks\Manipulate034.Rnw + .\English\Manipulate035.Rnw + .\RChunks\Manipulate036.Rnw + .\English\Manipulate037.Rnw + .\RChunks\Manipulate038.Rnw + .\English\Manipulate039.Rnw + .\RChunks\Manipulate040.Rnw + .\English\and.Rnw + .\RChunks\Manipulate042.Rnw + .\English\Manipulate043.Rnw + .\RChunks\CleanUp.Rnw Manipulate.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\Maps001.Rnw + .\RChunks\Maps002.Rnw + .\English\Maps003.Rnw + .\RChunks\Maps004.Rnw + .\English\Maps005.Rnw + .\RChunks\Maps006.Rnw + .\English\Maps007.Rnw + .\RChunks\Maps008.Rnw + .\English\Maps009.Rnw + .\RChunks\Maps010.Rnw + .\RChunks\CleanUp.Rnw Maps.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\Multivariate001.Rnw + .\RChunks\Multivariate002.Rnw + .\English\Multivariate003.Rnw + .\RChunks\Multivariate004.Rnw + .\English\Multivariate005.Rnw + .\RChunks\CleanUp.Rnw Multivariate.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\NumericalEDA001.Rnw + .\RChunks\NumericalEDA002.Rnw + .\English\NumericalEDA003.Rnw + .\RChunks\NumericalEDA004.Rnw + .\English\NumericalEDA005.Rnw + .\RChunks\NumericalEDA006.Rnw + .\English\NumericalEDA007.Rnw + .\RChunks\NumericalEDA008.Rnw + .\English\NumericalEDA009.Rnw + .\RChunks\NumericalEDA010.Rnw + .\English\NumericalEDA011.Rnw + .\RChunks\AttachAirquality.Rnw + .\RChunks\NumericalEDA012.Rnw + .\English\NumericalEDA013.Rnw + .\RChunks\NumericalEDA014.Rnw + .\English\NumericalEDA015.Rnw + .\RChunks\NumericalEDA016a.Rnw +.\English\or.Rnw+ .\RChunks\NumericalEDA016b.Rnw + .\English\NumericalEDA017.Rnw + .\RChunks\NumericalEDA018.Rnw + .\English\NumericalEDA019.Rnw + .\RChunks\NumericalEDA020.Rnw + .\English\NumericalEDA021.Rnw + .\RChunks\NumericalEDA022.Rnw + .\English\NumericalEDA023.Rnw + .\RChunks\NumericalEDA024.Rnw + .\English\NumericalEDA025.Rnw + .\RChunks\NumericalEDA026.Rnw + .\English\NumericalEDA027.Rnw + .\RChunks\NumericalEDA028.Rnw + .\English\NumericalEDA029.Rnw + .\RChunks\NumericalEDA030.Rnw + .\English\NumericalEDA031.Rnw + .\RChunks\NumericalEDA032.Rnw + .\English\NumericalEDA033.Rnw + .\RChunks\NumericalEDA034.Rnw + .\English\NumericalEDA035.Rnw + .\RChunks\NumericalEDA036.Rnw + .\English\NumericalEDA037.Rnw + .\RChunks\dplyr.Rnw + .\English\NumericalEDA039.Rnw + .\RChunks\NumericalEDA040.Rnw + .\English\NumericalEDA041.Rnw + .\RChunks\NumericalEDA042.Rnw + .\English\NumericalEDA043.Rnw + .\RChunks\NumericalEDA044.Rnw + .\English\NumericalEDA045.Rnw + .\RChunks\NumericalEDA046.Rnw + .\English\NumericalEDA047.Rnw + .\RChunks\NumericalEDA048.Rnw + .\English\NumericalEDA049.Rnw + .\RChunks\NumericalEDA050.Rnw + .\English\NumericalEDA051.Rnw + .\RChunks\DetachAirQuality.Rnw + .\RChunks\CleanUp.Rnw NumericalEDA.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\QualityControl001.Rnw + .\RChunks\QualityControl002.Rnw + .\English\QualityControl003.Rnw + .\RChunks\QualityControl004.Rnw + .\English\QualityControl005.Rnw + .\RChunks\QualityControl006.Rnw QualityControl.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\Regression001.Rnw + .\RChunks\Regression002.Rnw + .\English\Regression003.Rnw + .\RChunks\Regression004.Rnw + .\English\Regression005.Rnw + .\RChunks\Regression006.Rnw + .\English\Regression007.Rnw + .\RChunks\Regression008.Rnw + .\English\Regression009.Rnw + .\RChunks\Regression010.Rnw + .\RChunks\Regression012.Rnw + .\English\Regression013.Rnw + .\RChunks\Regression014.Rnw + .\English\Regression015.Rnw + .\RChunks\Regression016.Rnw + .\English\Regression017.Rnw + .\RChunks\Regression018.Rnw + .\English\Regression019.Rnw + .\RChunks\Regression020.Rnw + .\English\Regression021.Rnw + .\RChunks\Regression022.Rnw + .\English\Regression023.Rnw + .\RChunks\Regression024.Rnw + .\English\Regression025.Rnw + .\RChunks\Regression026.Rnw + .\English\Regression027.Rnw + .\RChunks\Regression028.Rnw + .\English\Regression029.Rnw + .\RChunks\Regression030.Rnw + .\English\Regression031.Rnw + .\RChunks\Regression032.Rnw + .\English\Regression033.Rnw + .\RChunks\Regression034.Rnw + .\English\Regression035.Rnw + .\RChunks\Regression036.Rnw + .\English\Regression037.Rnw + .\RChunks\CleanUp.Rnw Regression.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\Scientific001.Rnw + .\RChunks\Scientific002.Rnw + .\English\Scientific003.Rnw + .\RChunks\Scientific004.Rnw + .\English\Scientific005.Rnw + .\RChunks\CleanUp.Rnw Scientific.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\SimpleGraphs001.Rnw + .\RChunks\SimpleGraphs002.Rnw + .\English\SimpleGraphs003.Rnw + .\RChunks\SimpleGraphs004.Rnw + .\English\SimpleGraphs005.Rnw + .\RChunks\AttachAirquality.Rnw + .\English\SimpleGraphs007.Rnw + .\RChunks\SimpleGraphs008.Rnw + .\English\SimpleGraphs009.Rnw + .\RChunks\SimpleGraphs010.Rnw + .\English\SimpleGraphs011.Rnw + .\RChunks\SimpleGraphs012.Rnw + .\English\SimpleGraphs013.Rnw + .\RChunks\SimpleGraphs014.Rnw + .\English\SimpleGraphs015.Rnw + .\RChunks\SimpleGraphs016.Rnw + .\English\SimpleGraphs017.Rnw + .\RChunks\SimpleGraphs018.Rnw + .\English\SimpleGraphs019.Rnw + .\RChunks\SimpleGraphs020.Rnw + .\English\SimpleGraphs021.Rnw + .\RChunks\SimpleGraphs022.Rnw + .\English\SimpleGraphs023.Rnw + .\RChunks\SimpleGraphs024.Rnw + .\English\SimpleGraphs025.Rnw + .\RChunks\SimpleGraphs026.Rnw + .\English\SimpleGraphs027.Rnw + .\RChunks\SimpleGraphs028.Rnw + .\English\SimpleGraphs029.Rnw + .\RChunks\SimpleGraphs030.Rnw + .\English\SimpleGraphs031.Rnw + .\RChunks\SimpleGraphs032.Rnw + .\English\SimpleGraphs033.Rnw + .\RChunks\SimpleGraphs034.Rnw + .\English\SimpleGraphs035.Rnw + .\RChunks\SimpleGraphs036.Rnw + .\English\SimpleGraphs037.Rnw + .\RChunks\SimpleGraphs038.Rnw + .\English\SimpleGraphs039.Rnw + .\RChunks\SimpleGraphs040.Rnw + .\English\SimpleGraphs041.Rnw + .\RChunks\SimpleGraphs042.Rnw + .\English\SimpleGraphs043.Rnw + .\RChunks\SimpleGraphs044.Rnw + .\English\SimpleGraphs045.Rnw + .\RChunks\DetachAirQuality.Rnw  + .\RChunks\CleanUp.Rnw SimpleGraphs.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\StoreResults001.Rnw + .\RChunks\StoreResults002.Rnw + .\English\StoreResults003.Rnw + .\RChunks\StoreResults004.Rnw + .\English\StoreResults005.Rnw + .\RChunks\StoreResults006.Rnw + .\English\StoreResults007.Rnw + .\RChunks\StoreResults008.Rnw + .\English\StoreResults009.Rnw + .\RChunks\StoreResults010.Rnw + .\English\StoreResults011.Rnw + .\RChunks\StoreResults012.Rnw + .\English\StoreResults013.Rnw + .\RChunks\StoreResults014.Rnw + .\English\StoreResults015.Rnw + .\RChunks\CleanUp.Rnw StoreResults.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\TimeSeries001.Rnw + .\RChunks\TimeSeries002.Rnw + .\English\TimeSeries003.Rnw + .\RChunks\TimeSeries004.Rnw + .\English\TimeSeries005.Rnw + .\RChunks\TimeSeries006.Rnw + .\English\TimeSeries007.Rnw + .\RChunks\TimeSeries008.Rnw + .\English\TimeSeries009.Rnw + .\RChunks\TimeSeries010.Rnw + .\English\TimeSeries011.Rnw + .\RChunks\TimeSeries012.Rnw + .\English\TimeSeries013.Rnw + .\RChunks\TimeSeries014.Rnw + .\English\TimeSeries015.Rnw + .\RChunks\TimeSeries016.Rnw + .\English\TimeSeries017.Rnw + .\RChunks\TimeSeries018.Rnw + .\English\TimeSeries019.Rnw + .\RChunks\TimeSeries020.Rnw + .\English\TimeSeries021.Rnw + .\RChunks\TimeSeries022.Rnw + .\English\TimeSeries023.Rnw + .\RChunks\TimeSeries024.Rnw + .\English\TimeSeries025.Rnw + .\RChunks\TimeSeries026.Rnw + .\English\TimeSeries027.Rnw + .\RChunks\TimeSeries028.Rnw + .\English\TimeSeries029.Rnw + .\RChunks\TimeSeries030.Rnw + .\English\TimeSeries031.Rnw + .\RChunks\CleanUp.Rnw TimeSeries.Rnw

copy .\RChunks\GenericSettings.Rnw + .\English\VI001.Rnw + .\RChunks\VI002.Rnw + .\English\VI003.Rnw + .\RChunks\VI004.Rnw + .\English\VI005.Rnw + .\RChunks\VI006.Rnw + .\English\VI007.Rnw + .\RChunks\VI008.Rnw + .\English\VI009.Rnw + .\RChunks\VI010.Rnw + .\English\VI011.Rnw + .\RChunks\VI012.Rnw + .\English\VI013.Rnw + .\RChunks\VI014.Rnw + .\English\VI015.Rnw + .\RChunks\VI016.Rnw + .\English\and.Rnw + .\RChunks\VI018.Rnw + .\English\VI019.Rnw + .\RChunks\VI020.Rnw + .\English\VI021.Rnw + .\RChunks\VI022.Rnw + .\English\VI023.Rnw + .\RChunks\VI024.Rnw + .\English\VI025.Rnw + .\RChunks\VI026.Rnw + .\English\VI027.Rnw + .\RChunks\CleanUp.Rnw VI.Rnw


copy .\RChunks\GenericSettings.Rnw + .\RChunks\OperRes002.Rnw + .\English\OperRes003.Rnw + .\RChunks\OperResAssignment.Rnw + .\English\OperRes005.Rnw + .\RChunks\CleanUp.Rnw OperRes.Rnw
