 
This printout isn't particularly attractive, but it is quick and informative. If presentation was more important than getting results efficiently, we would look to improve the appearance --- this means more difficult coding though. 
 
There is one more feature of the \Rcmd{tapply} command that must be pointed out. The simple commands shown thus far use the default settings of the relevant functions. In particular, the \Rcmd{mean} command does not ignore missing values by default. 
