 
This chapter presents the most basic regression models. To really get the most out of \R{} and regression techniques (such as those taught in second or later statistics courses) you will need to look for guidance from a suitable textbook, many of which incorporate use of \R{} as the preferred software tool. 
 
\section{Data and suitable exploratory graphs} 
 
The easiest way to fit regression models is using data that are contained in a \Rclass{data.frame}. This means we can use the \Rcmd{attach} command to get at the separate components if we need them. An alternative is to have direct access to each variable independently within our current workspace. For neatness, I prefer to keep data in the \Rclass{data.frame} format. 
 
We can use the \Robject{air quality} data described in Chapter~\ref{SimpleGraphs}. Recall that it is available from your current workspace as it is contained within the \Rpackage{datasets} package. Typing 
