will save all the issued commands into a text file called \file{WhatIDidToday.txt} in the working directory.  
 
If I just want to have everything I do during a session recorded for posterity, I want all contents of the console window to be saved. A plain text file is sufficient but it is possible to use add-on packages to create other file formats. 
 
I have included a convenience function in the \Rpackage{BrailleR} package that starts a text file with the date and time in its filename. It gets saved in the current working directory. To get this file started, just type 
