% filename Calculus005.Rnw 

\SVGLink{CalculusSineCurve-1} 
 
You can use any valid mathematical expression in the \Rclass{function} you create. You might find it useful to test your idea= values for your inputs that are easy to work with, such as zero and one. You could then use integers, including negative integers, but  it could be easier to test your functions using values that lead to identifiable results such as multiples of $\pi$ when working with trignometric functions. For example: 
