% filename NumericalEDA007.Rnw 

The \Rcmd{summary} command finds the common numeric summary statistics for the continuous-valued variables and does a particulary useless job on the variables for month and day. Well it's not really \R{}'s fault. The month didn't need to be stored numerically, but in any case we got what we asked for! It's not \R{}'s fault we asked to be told what the minimum day number was! 
 
Notice that the \Rcmd{summary} command extracted the minimum, maximum, median and mean for the variables in the \Rclass{data.frame}. These are all available using corresponding \Rcmd{min}, \Rcmd{max}, \Rcmd{median}, and \Rcmd{mean} commands separately but they work in different ways on data frames. For example we might have thought to use the \Rcmd{mean} command on a \Rclass{data.frame}, but it is better practice to use the more specific \Rcmd{colMeans} command instead. 
