Notice that a consequence of missing values in our data is that some functions will return the \code{NA} value. If we want the quantity returned to be estimated using the available data we simply add the argument \Rarg{na.rm=TRUE} which removes the values denoted with the \code{NA}. 
 
The first and third quartiles are not so easily extracted however. We can get the first and third quartiles from the five number summary by extracting elements of the output returned by the \Rcmd{fivenum} command. For example 
