 
This chapter takes a basic look at the methods of quality control. This material is not always taught in first year statistics courses and is often one of those topics that some people think can be ignored. I guess you can tell what I think given the inclusion of this topic in this document. Like many other topics, you'll need to consult a suitable textbook for a thorough examination of the topic. Some would call quality control or quality improvement a discipline not just a topic. 
 
As quality control methods are not yet implemented in the base distribution of \R{}, you will need to obtain the \Rpackage{qcc} package from CRAN, and install it. This can be done using the menus, command lines, or using file management techniques from within your operating system. 
 
Once it is installed properly, you can access the contents of the package by issuing the command 
