% filename Regression015.Rnw 

\end{center} 
\end{exhibit} 
These plots are enhanced by \R{} to add more information than the basic user is familiar with. Additional lines are added to three of the plots to assist in diagnosing problems. We can see from this plot that the model is inadequate as there is a nonlinear relationship between the response and predictor, and further that the residuals might not have very constant variance. 
 
It might be easier to extract just the information we want, so we can build simpler plots ourselves. We need to find the residuals, fitted values and leverages for the model. These are found using the \Rcmd{resid}, \Rcmd{fitted}, and \Rcmd{hatvalues} commands respectively. 
