% filename SimpleGraphs009.Rnw 

\end{center} 
\end{exhibit} 

\Blind{\subsection*{A note on the visual appearance of the standard histogram for blind users}

\Sexpr{Describe(hist(Wind))$general}
} 

\section{Basic annotations to graphs} 
 
\begin{exhibit} 
\begin{center} 
\caption{Histogram of Average wind speed at 0700 and 1000 hours at New York's LaGuardia Airport. Obtained from the \Robject{air quality} data set.} 
\label{AirQualityHistWind2} 
