 
This chapter illustrates the construction of some basic exploratory data analysis graphs. More complex graphs are considered in Chapter~\ref{ComplexGraphs}, although at times we will see graphs presented in conjunction with particular statistical analysis techniques. We concentrate on data taking continuous values initially, but a short section on graphs for discrete valued variables is included at the end. 
 
We will use the \Robject{air quality} data set that is distributed in the \Rpackage{datasets} package which is part of the default installation of \R{}. This data set is immediately accessible from your \R{} session and can be investigated using 
