% filename VI014.Rnw 

<<Hist, fig.show="hide">>= 
VI(hist(airquality$Wind, xlab="Average wind speed (mph)", main="")) 
@
\includegraphics[width=0.8\textwidth,alt={a histogram}]{figures/VIHist-1} 
<<HistSVG, echo=FALSE, include=FALSE, messages=FALSE, warnings=FALSE, results="hide">>= 
MakeAccessibleSVG(hist(airquality$Wind, xlab="Average wind speed (mph)", main=""), "figures/VIHistAirQualityWind") 
@ 
\SVGLink{VIHistAirQualityWind} 
